project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
    - "blog/**/*.qmd"
    - "talk/**/*.qmd"
    - "project/**/*.qmd"
    - "about/index.*md"
  preview: 
    browser: true
  #output-dir: docs


website:
  title: "SARA INSTITUTE"
  favicon: "images/logo-sara.png"
  site-url: "https://sara-edu.netlify.app/"
  description: "The best data science education is free and open-source. SARA is committed to provide free data science education to under-represented communities in India."
  twitter-card: 
    creator: "@sara_institute"
    site: "@sara_institute"
    card-style: summary_large_image
    image: social-default.png
  cookie-consent: false
  announcement:
    #icon: book
    dismissable: true
    content: "🎉 SARA Annual Report 2026 [Link](https://speakerdeck.com/sara2023/sara-annual-report-2025-26-84ca232d-d25f-478a-9a4d-5d7b52814730

Dear 700+ SARA Supporter,

We are very thankful for your lovely support to SARA. 

Kindly glance through SARA Report 2025-26. Let's know your feedback to improve SARA.

Regards) "
    type: success
    position: below-navbar
  

  navbar:
    search: true
    pinned: true
    right:
      # - text: Home
      #   href: index.qmd
      - text: About
        menu: 
          - text: Mission  
            href: about.qmd
          - text: Timeline
            href: timeline.qmd
          - text: Annual Report
            href: annual-report.qmd
      - text: Data Schools 
        menu:
          - text: Summer School
            href: summer.qmd
          - text: Winter School
            href: winter.qmd
          - text: Coding Bootcamp
            href: bootcamp.qmd      
      - text: Bridge Courses
        menu: 
          - text: Offline Courses
            href: offline.qmd
          - text: Online Courses
            href: online.qmd
          # - text: Python Language
          #   href: python-course/python-course.qmd  

      - text: Book Club
        href: book-club.qmd
      - text: Collaborations
        href: workshops.qmd
      - text: News
        href: news.qmd
      - text: Donate 
        href: donate.qmd
      # - text: Contact
      #   href: contact.qmd
        
      
  page-footer:
    background: "#003262"
    left: "SARA Institute &copy; 2023-2026"
    center:
      - text: "{{< iconify fa6-brands bluesky >}}"
        href: https://bsky.app/profile/sarainstitute.bsky.social  
      - icon: twitter-x
        href: https://twitter.com/sara_institute
        aria-label: Twitter
      - icon: instagram
        href: https://www.instagram.com/sara_data_sci/
        aria-label: Twitter  
      - icon: github
        href: https://github.com/sara-institute
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/company/sara-institute/
        aria-label: LinkedIn
      - icon: youtube
        href: https://www.youtube.com/@SARADataScience
        aria-label: YouTube  
      - icon: whatsapp
        href: https://whatsapp.com/channel/0029Va4r7rGLCoWycMwThl2J
        aria-label: WhatsApp  
  
    right: "[Privacy](privacy.qmd) | [Terms & Conditions](terms.qmd)"
    border: true
    
    
format:
  html:
    page-layout: full
    theme: 
     - flatly
     - test.scss
    css: styles.css
    toc: false

execute:
  freeze: auto
  