project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
    - "blog/**/*.qmd"
    - "talk/**/*.qmd"
    - "project/**/*.qmd"
    - "about/index.*md"
  preview: 
    browser: true
  #output-dir: docs

website:
  title: "SARA INSTITUTE"
  favicon: "images/logo-sara.png"
  site-url: "https://sara-edu.netlify.app/"
  description: "The best data science education is free and open-source. SARA is committed to provide free data science education to under-represented communities in India."
  twitter-card: 
    creator: "@sara_institute"
    site: "@sara_institute"
    card-style: summary_large_image
    image: social-default.png
  cookie-consent: false
  #announcement:
    #icon: stars
    #dismissable: true
    #content: "banner ribbon"
    #type: danger
    #position: below-navbar
  
  
  navbar:
    search: false
    pinned: false
    right:
      - text: Home
        href: index.qmd
      - text: About
        menu: 
          - text: Mission  
            href: about.qmd
          - text: Timeline
            href: timeline.qmd
          - text: Annual Report
            href: report.qmd
      - text: Courses
        menu: 
          - text: Computer Skills
            href: computer-course/computer-course.qmd
          - text: English Language
            href: english-course/english-course.qmd
      - text: Trainings
        menu:
          - text: Research Methods
            href: rm-summer/2025-summer-school/summer-school-2025.qmd
          - text: R Langauge
            href: r-bootcamp/2024-r-lang/r-bootcamp-2024.qmd  
          - text: Statistics using R
            href: stats-winter/2024-stats-winter/stats-winter-2024.qmd
          - text: Publish using Quarto
            href: publish-bootcamp/2025-publish-bootcamp/publish-bootcamp-2025.qmd
      - text: News & Events
        href: news.qmd
      - text: Support 
        href: support.qmd
      - text: Contact
        href: contact.qmd
        
     
       
        
  page-footer:
    background: "#003262"
    left: "SARA Institute &copy; 2023-2025"
    center:
      - text: "{{< iconify fa6-brands bluesky >}}"
        href: https://bsky.app/profile/sarainstitute.bsky.social  
      - icon: twitter-x
        href: https://twitter.com/sara_institute
        aria-label: Twitter
      - icon: github
        href: https://github.com/sara-institute
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/company/sara-institute/
        aria-label: LinkedIn
      - icon: youtube
        href: https://www.youtube.com/@SARADataScience
        aria-label: YouTube  
      - icon: whatsapp
        href: https://whatsapp.com/channel/0029Va4r7rGLCoWycMwThl2J
        aria-label: WhatsApp  
  
    right: "[Privacy](privacy.qmd) | [Terms & Conditions](terms.qmd)"
    border: true
    
      
format:
  html:
    page-layout: full
    theme: 
     - flatly
     - test.scss
    css: styles.css
    toc: false

execute:
  freeze: auto