---
pagetitle: "Contact"
#page-layout: full
#backgroundcolor: "#e9e9e9"
#format: html
#css: styles.css
include-in-header: 
  text: |
    <style type="text/css">
      h2, .h2 {
        border-bottom: none;
      }
    </style>
---

# Contact Us

::: {.col}
::: {.card}

**Get in Touch with SARA Institute of Data Science**

We welcome your inquiries, feedback, and collaboration opportunities. Please feel free to reach out to us using any of the following methods:

<br>

**{{< fa university >}} Address:**<br>
SARA Institute.   
Dr. Ambedkar Bhavan.    
Kakroi Road, Sonipat.        
Haryana - 131001, India.       
Google Map Link: <https://maps.app.goo.gl/d9S6a3pEFNXhnJGN6>

<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d17631.750001600412!2d77.0063004!3d28.9874932!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390dbb4946f90a19%3A0xafa9442f42980f24!2sDr.%20Ambedkar%20Bhawan!5e1!3m2!1sen!2sin!4v1730708429842!5m2!1sen!2sin" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

<br>

**{{< fa phone >}} Phone:**<br>
Main Office: +91 925 315 2024 

<br>

**{{< fa envelope >}} Email:**<br>
General & donation inquiries: <sara.institute.info@gmail.com>

<br>

**Social Media:**<br>
Connect with us on our social media platforms to stay updated on our latest news, events, and initiatives.<br>

<br>[{{< fa brands github size=2x >}}](https://github.com/sara-edu) &nbsp;[{{< fa brands twitter size=2x >}}](https://twitter.com/sara_institute) &nbsp; [{{< fa brands facebook size=2x >}}](https://www.facebook.com/profile.php?id=61564043738390) &nbsp; [{{< fa brands youtube size=2x >}}](https://www.youtube.com/@SARADataScience) &nbsp; [{{< fa brands linkedin size=2x >}}](https://www.linkedin.com/company/sara-institute/) &nbsp; [{{< fa brands whatsapp size=2x >}}](https://whatsapp.com/channel/0029Va4r7rGLCoWycMwThl2J)

<br>

**Visit Us:**<br>
We encourage you to visit our institute and witness firsthand the impact of our educational programs. Schedule a visit by contacting our office.

{{< fa clock >}} Office hours: Monday to Friday, from 09 AM to 06 PM.

<!-- **Feedback:**<br> -->
<!-- Your feedback is invaluable to us. Please let us know how we can improve our services or share your experiences with us by filling out our feedback form [link to feedback form]. -->

Thank you for your interest in the SARA Institute. We look forward to hearing from you soon!

:::
:::

<br>
