---
title: |
    <br>[Summer School 2025: Research Design & Methods]{style="color:#228B22"}\
#subtitle: "SARA Summer School, 23-27 April 2025"
pagetitle: "SARA RM"
toc: false
include-in-header: 
  text: |
    <style type="text/css">
      h2, .h2 {
        border-bottom: none;
      }
    </style>
---

[Join us this April 2025 for our immersive summer school program, **"Research Design & Methods: From Theory to Practice using R."** This comprehensive course is designed to equip you with the essential skills to conduct robust research and analyze data effectively using R.]{.p-mission}

:::: col
::: card
## [What to Expect:]{style="color:#228B22"}

-   **Hands-On Learning**: Dive into practical sessions that bridge the gap between theoretical knowledge and real-world application.
-   **Expert Guidance**: Learn from experienced instructors who will guide you through every step of the research process.
-   **Collaborative Environment**: Engage with fellow participants and build a network of peers passionate about data-driven research.
-   **Inclusive and Accessible**: Our program is open to everyone, regardless of background or experience level.

## [Why Attend?]{style="color:#228B22"}

-   **Enhance Your Skills**: Gain proficiency in research design, data analysis, and the use of R for statistical computing.
-   **Boost Your Career**: Acquire valuable skills that are in high demand across various industries.
-   **Make an Impact**: Learn how to apply research methods to address real-world challenges and drive meaningful change.

## [Program Details:]{style="color:#228B22"}

-   **Dates**: 20-26 April 2025
-   **Duration**: 7 days
-   **Fee**: ₹6,000 INR (Inclusive of food and accommodation)
-   **Early Bird Discount**: The first 10 registered participants will receive a 25% discount!
-   **Payment**: You can secure your spot by making the payment via UPI. Our UPI ID is `919253152024@sbi`.
-   **Location**: SARA Institute, Dr. Ambedkar Bhavan, Kakroi Road (near Dayanand Hospital), Sonipat, Haryana - 131001.

As a non-profit organization, SARA is committed to making education accessible to all. The fee covers only the essential costs of food and accommodation, ensuring that everyone has the opportunity to participate.

Don't miss this opportunity to advance your research capabilities and join a community of like-minded individuals. Register now and take the first step towards mastering research design and methods with R!

## [Registration:]{style="color:#228B22"} <https://tinyurl.com/mr3e2t7c> (Last Date of Registration: 18 April 2025)

For more information, please contact us at [sara.institute.info\@gmail.com](mailto:sara.institute.info@gmail.com){.email} or call us 925 315 2024.

We look forward to seeing you at the summer school!
:::
::::

<br>

:::: col
::: card
## [Schedule]{style="color:#228B22"}

Arrival of participants on Sunday 20 April 2025.

| Topics (21-25 April 2025)                    | Hours |
|:---------------------------------------------|-------|
| Foundations + Ethics                         | 5     |
| Quantitative Methods (Experiments & Surveys) | 8     |
| Qualitative Methods                          | 6     |
| Mixed Methods + Data Tools                   | 4     |
| Analysis, Reporting, Final Project Workshop  | 7     |

Departure of participants on Saturday 26 April 2025.
:::
::::

<br>

:::: col
::: card
## More Information Coming Soon!
:::
::::

<br>
